export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import MobileNavbar from "@/components/MobileNavbar";
import "../globals.css";
import StoreProvider from "../StoreProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
          <StoreProvider>
          <body>
          <MobileNavbar />
            {children}
          </body>
        </StoreProvider>
    </html>
  )
}
